name: Build and Release (Cross Matrix)
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'Cross.toml'
      - 'rust-toolchain.toml'
      - '.cargo/**'
      - '.github/workflows/build.yml'

permissions:
  contents: read

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10

jobs:
  build:
    name: Build (${{ matrix.platform.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-unknown-linux-gnu
            name: linux-amd64
            is_android: false
          - target: aarch64-unknown-linux-gnu
            name: linux-arm64
            is_android: false
          - target: aarch64-linux-android
            name: android-arm64
            is_android: true
          - target: armv7-linux-androideabi
            name: android-arm
            is_android: true
          - target: i686-unknown-linux-gnu
            name: linux-i686
            is_android: false
          - target: s390x-unknown-linux-gnu
            name: linux-s390x
            is_android: false
          - target: x86_64-pc-windows-gnu
            name: windows-amd64
            is_android: false
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.platform.target }}

      - name: Setup Android NDK
        if: matrix.platform.is_android == true
        uses: nttld/setup-ndk@v1.6.0
        with:
          ndk-version: r29
          add-to-path: true
          local-cache: true

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2.9.1
        with:
          shared-key: release
          key: ${{ matrix.platform.target }}
          workspaces: |
            . -> target
          cache-bin: false
          cache-on-failure: true

      - name: Install cargo-ndk
        if: matrix.platform.is_android == true
        uses: taiki-e/install-action@v2.84.0
        with:
          tool: cargo-ndk@4.1.2

      - name: Install Cross
        if: matrix.platform.is_android != true
        uses: taiki-e/install-action@v2.84.0
        with:
          tool: cross@0.2.5

      - name: Run Cargo NDK Build (Android)
        if: matrix.platform.is_android == true
        run: |
          cargo ndk --target ${{ matrix.platform.target }} --platform 24 build --release --locked

      - name: Run Cross Build (Non-Android)
        if: matrix.platform.is_android != true
        run: |
          cross build --release --locked --target ${{ matrix.platform.target }}

      - name: Package Artifacts
        run: |
          mkdir -p ./dist
          mkdir -p ./pkg_dir
          FILE_PATH="target/${{ matrix.platform.target }}/release/wuther-core"

          if [ -f "target/${{ matrix.platform.target }}/release/wuther-core.exe" ]; then
            FILE_PATH="target/${{ matrix.platform.target}}/release/wuther-core.exe"
          fi

          if [ -f "$FILE_PATH" ]; then
            cp "$FILE_PATH" ./pkg_dir/
          else
            echo "Error: Failed to find artifacts $FILE_PATH"
            exit 1
          fi

          cd ./pkg_dir
          zip -r ../dist/wuther-core-${{ matrix.platform.name }}.zip ./*
          cd ..

      - name: Upload Artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: wuther-core-${{ matrix.platform.name }}
          path: ./dist/wuther-core-${{ matrix.platform.name }}.zip
          if-no-files-found: error
          compression-level: 0
          retention-days: 1
